# Generated by Django 5.2.4 on 2025-07-18 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification of listing', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title or name of listing', max_length=100)),
                ('description', models.TextField(help_text='Description of listing')),
                ('location', models.CharField(help_text='Location of listing', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of listing', max_digits=10)),
                ('type', models.CharField(help_text='Type of listing', max_length=100)),
                ('host', models.ForeignKey(help_text='Host of listing', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
