# Generated by Django 5.2.4 on 2025-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('ROOM', 'Room'), ('TOUR', 'Tour'), ('Car', 'Car')], help_text='Type of listing', max_length=20),
        ),
    ]
