# Generated by Django 5.2.4 on 2025-07-18 08:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time of listing creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of last update of listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('ROOM', 'Room'), ('TOUR', 'Tour'), ('CAR', 'Car')], help_text='Type of listing', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HOST', 'Host'), ('GUEST', 'Guest')], default='GUEST', help_text='Type of user', max_length=10),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification of booking', primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price of listing', max_digits=10)),
                ('check_in', models.DateField(help_text='Check in date of guest')),
                ('check_out', models.DateField(help_text='Check out date of guest')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of booking creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of last update of booking')),
                ('guest', models.ForeignKey(help_text='Guest that is booked the listing', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Listing that has been booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification of review', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating of review between 1 and 5')),
                ('comment', models.TextField(blank=True, help_text='Review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of review creation')),
                ('guest', models.ForeignKey(help_text='Guest giving review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Listing being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
